node{
	def mvnHome
	def dockerHome
	stage('Checkout'){
		git url: 'file://E:/LTI-July/workspace/aws-demo', branch: 'master'
		mvnHome = tool 'Local Maven'
		dockerHome = tool 'MyDocker'
	}
	stage('Build'){
		bat(/"${mvnHome}\bin\mvn" clean package/)
	}
	stage('Create Image'){
		bat(/"${dockerHome}\Docker\resources\bin\docker" build -t jenkins-build:latest ./)
	}
	
	stage('Run'){
		bat(/"${dockerHome}\Docker\resources\bin\docker" run -p 5000:5000 jenkins-build:latest/)
	}
	
}
